### ISSUE TITLE
Simulator.py throws error when finding output directory

### ISSUE THREAD

**Issue by Deepika-Parthasarathy** [cellmodeller/CellModeller#47]
`(celmod) dinky@DESKTOP-DGB9GV7:~/CellModeller$ python3 Scripts/batch.py Examples/ex1_simpleGrowth.py
Select OpenCL platform:
press 0 for <pyopencl.Platform 'Portable Computing Language' at 0x7f702676d008>
Platform Number: 0
Select OpenCL device:
press 0 for <pyopencl.Device 'pthread-Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz' on 'Portable Computing Language' at 0x5568594c50e0>
Device Number: 0
Set up OpenCL context:
  Platform: Portable Computing Language
  Device: pthread-Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
Importing model ex1_simpleGrowth
Traceback (most recent call last):
  File "/home/dinky/CellModeller/Scripts/batch.py", line 54, in <module>
    main()
  File "/home/dinky/CellModeller/Scripts/batch.py", line 50, in main
    simulate(moduleName, platnum, devnum)
  File "/home/dinky/CellModeller/Scripts/batch.py", line 16, in simulate
    sim = Simulator(modname, 0.025, clPlatformNum=platform, clDeviceNum=device, saveOutput=True)
  File "/home/dinky/CellModeller/CellModeller/Simulator.py", line 109, in __init__
    self.setSaveOutput(saveOutput)
  File "/home/dinky/CellModeller/CellModeller/Simulator.py", line 117, in setSaveOutput
    self.init_data_output()
  File "/home/dinky/CellModeller/CellModeller/Simulator.py", line 135, in init_data_output
    os.mkdir(self.outputDirPath)
FileNotFoundError: [Errno 2] No such file or directory: 'data/ex1_simpleGrowth-23-08-16-11-38'`

I got this error running both in batch mode and from the GUI when I toggle the 'save pickles' 
I understand it is unable to create a directory or find it. But I am not sure on how to go about debugging this. 
I am on ubuntu LTS 22.04 and I am using VScode for debugging. Thanks.

**Comment by timrudge** [comment]
Hi - you need to make the directory ~/cellmodeller/data before running. Let
me know if that resolves the issue. Thanks,
Tim

**Comment by timrudge** [comment]
Wait sorry my mistake, try running from your ~/cellmodeller directory

**Comment by Deepika-Parthasarathy** [comment]
cellmodeller/data directory was created early on (as per the user guidelines) 
There exist two directories: 
1. CellModeller (cloned from git hub)
2. cellmodeller (directory created to store data in the home directory) 
I tried running the GUI from both and outside of both directories. It throws the same FileNotFoundError
`Traceback (most recent call last):
  File "/home/dinky/CellModeller/CellModeller/GUI/PyGLCMViewer.py", line 128, in toggleSavePickles
    self.sim.setSaveOutput(save)
  File "/home/dinky/CellModeller/CellModeller/Simulator.py", line 117, in setSaveOutput
    self.init_data_output()
  File "/home/dinky/CellModeller/CellModeller/Simulator.py", line 135, in init_data_output
    os.mkdir(self.outputDirPath)
FileNotFoundError: [Errno 2] No such file or directory: 'data/ex1_simpleGrowth-23-08-16-12-28'
saveOutput  True`

**Comment by avimanyu786** [comment]
@Deepika-Parthasarathy Are you trying to run it on CPU? You can try the docker containers. They would work for both CPU and GPU. For CPU, you can run a cellmodeller container without having to add any GPU options and it should run fine.

Here's the relevant documentation on our wiki for the docker method:

https://github.com/cellmodeller/CellModeller/wiki/Installation#alternate-method-docker-containers

**Comment by Deepika-Parthasarathy** [comment]
Hey Avimanyu, 
I followed those instructions, and was able to deploy the container. I haven't worked with docker before but I get errors with accessing packages I thought I had downloaded. Here is the snippet. 
<img width="965" alt="image" src="https://github.com/cellmodeller/CellModeller/assets/141874128/4931b2d7-786d-4210-b8a7-e8cf343de222">
I am not sure of what is to be done. I tried sudo apt install but that doesn't work? 
I am wondering if it has something to do with the ` -v /tmp/.X11-unix:/tmp/.X11-unix` argument? 
I can use some guidance with this.

**Comment by avimanyu786** [comment]
I see. Could you retry a new container again by adding `--device=/dev/dri` ? `/tmp/.X11-unix:/tmp/.X11-unix` is what allows running the cellmodeller graphics.

It would be great if you could also share your system specifications for understanding the issue better.

**Comment by Deepika-Parthasarathy** [comment]
okay. Here goes 
I am working on windows 11. I have got Ubuntu 22.04 installed on WSL. I have been trying to run cellmodeller on this. I hope this would be helpful.

**Comment by avimanyu786** [comment]
The Docker containers were built for Linux and haven't quite been tested on WSL. Since you are using Windows, you can refer to this tutorial: https://gist.github.com/waterfleas/f539dd69634cd65596641ca2c6df980b as mentioned earlier in https://github.com/cellmodeller/CellModeller/issues/36#issuecomment-989469169.
